[package]
name = "esox"
version = "0.2.0"
edition = "2021"
description = "Library for NISECI and HFBI calc"
license = "GPL-3.0-only"
repository = "https://github.com/JGGR/esox"
documentation = "https://docs.rs/esox/"
include = [
    "src/*",
    "LICENSE",
]

[features]
experimental = []
json = ["dep:json", "dep:serde_json"]

[dependencies]
chrono = { version = "0.4.45", default-features = false }
csv = "1.4.0"
hashbrown = { version = "0.17.1", default-features = false, features = ["default-hasher", "inline-more", "raw-entry", "serde"]}
json = { version = "0.12.4", optional = true }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", optional = true }

[dev-dependencies]
criterion = "0.8.2"
rand = "0.10.2"

[[bench]]
name = "niseci"
harness = false

[[bench]]
name = "hfbi"
harness = false
