[package]
name = "esox"
version = "0.1.4"
edition = "2021"
description = "Library for NISECI and HFBI calc"
license = "GPL-3.0-only"
repository = "https://github.com/JGGR/esox"
exclude = [
    ".github/**",
    "templates",
]

[features]
experimental = []
json = ["dep:json", "dep:serde_json"]

[dependencies]
chrono = { version = "0.4.44", default-features = false }
csv = "1.4.0"
json = { version = "0.12.4", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", optional = true }
